name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # 每12小時執行一次
  workflow_dispatch:  # 手動觸發
  push:
    branches: 
      - main
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=#ff6b35&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
      - name: Push snake files to output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
