name: Generate Multiple Snake Themes

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate multiple snake themes
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-light.svg?palette=github-light
            dist/ocean.gif?color_snake=#06b6d4&color_dots=#0d1117,#1e3a8a,#3b82f6,#f59e0b,#f97316
            dist/sunset.gif?color_snake=#ff6b35&color_dots=#2d1b69,#8b1538,#d63031,#fd7f28,#fdcb6e
            dist/forest.gif?color_snake=#2ed573&color_dots=#0d1117,#1a472a,#2d5a3d,#42a047,#6abf69
            dist/aurora.gif?color_snake=#8b5cf6&color_dots=#111827,#1e40af,#8b5cf6,#06b6d4,#10b981
      
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
